# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BankUI

  pod 'RealmSwift'
  pod 'GoogleMaps'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'Firebase/Analytics'
end
