# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'BankUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BankUI

  pod 'RealmSwift'
  pod 'GoogleMaps'
  pod 'FirebaseCrashlytics'
  pod 'Firebase/Analytics'
end
